version: '3'

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    command: npm run dev:start
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - type: bind
        source: ./src
        target: /app/src
        read_only: true
    ports:
      - "3000:3000"
      - "9229:9229"
